name: build-osx

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]

    name: Build ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Check go install
      run: go version

    - name: Install Mac dependencies
      run: brew install sdl2
    
    - name: Build universal binary
      run: |
        git describe --tags --abbrev=8 --dirty --always --long > resources/version.txt
        CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -tags static -o vice_amd64 .
        CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -tags static -o vice_arm64 .
        lipo -create -output vice vice_amd64 vice_arm64

    - name: Save executable as build artifact
      uses: actions/upload-artifact@v3
      with:
        name: vice-osx
        path: vice
